### PR TITLE
Added Italian translations

### PR DESCRIPTION
**Pull request by AlessandroLevante**
Added full Italian translation for the role Jester.

### CODE REVIEW

**Comment by Alf21** [comment]
Thanks for your PullRequest :)

Is it tested? Because I don't know whether e.g. this line is working correctly: `L["hilite_win_" .. JESTER.defaultTeam] = "I JESTER HANNO VINTO"` (l. 4, whether JESTER is already defined atm)

**Comment by AlessandroLevante** [comment]
I'm not sure, I'm playing on an Italian server using these translations but there the Jester can't win, so this line will never show up. If somebody tests it and it doesn't work, I'll change it!

**Comment by TimGoll** [comment]
I'm pretty sure that this does not work. The language identifier has to stay untouched

**Comment by AlessandroLevante** [comment]
I don't know, it seems right to me, when I have some time I will try but I can't on the server I play

**Comment by ThePlatinumGhost** [comment]
@PinoMartirio there are no problem, i can test this thing with you
You only need to ask
I simply change the winstate e lets see if all work

**Comment by ThePlatinumGhost** [comment]
ttt_community_pool0007
It works without problems

**Comment by TimGoll** [comment]
I see, nice

**Review by TimGoll — APPROVED** [review]

**Review by Alf21 — APPROVED** [review]

**Pull request merged**
