### PR TITLE
Added winstate 8

### PR DESCRIPTION
**Pull request by hotdog218**
Winstate 8 is an instant jester win if they are killed by an innocent, but not by traitors or serial killers.

Particularly useful if you set `self.visibleForTraitors = false`.

### CODE REVIEW

**Review by Histalek — APPROVED** [review]
This looks fine to me, but mind the `"TTT2PreventJesterWinstate"` hook. Because right now if the Infected kills the Jester they will not win.

**Comment by hotdog218** [comment]
Ah. I don't have the infected role on my server so I didn't think of this, but good to keep in mind.

**Comment by TimGoll** [comment]
You can edit your pullrequest without closing it

**Comment by hotdog218** [comment]
Ah, sorry I'm not too familiar with GitHub. I'll see if I can fix it.

**Comment by hotdog218** [comment]
I don't know a ton of lua (in fact I'm still actively trying to learn the majority of it), so hopefully that should be fine. I initially created this just for my server, so no worries if you don't want to implement it. It works fine for my purposes :)

**Comment by TimGoll** [comment]
@Histalek since you are assigned to this you might want to take a look at this. Is this still relevant? Should it be modified, merged or rejected?

**Comment by Histalek** [comment]
i'm still fine with it getting merged as i will be unable to work on a jester rework (on a conceptual level) as of now. Why i'm assigned to this i frankly don't know =D

**Comment by TimGoll** [comment]
since the jester got completely reworked, this no longer is needed.

**Pull request closed without merging**
